### 결제 계산 성공 , 하나
### 1 = 3000 | 2 = 2000
### 예상값 = 12000
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "count": 3
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": false
}

### 결제 계산 성공 , 여러개
### 1 = 3000 | 2 = 2000
### 예상값 = 14000
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "count": 3
    },
    {
      "id": 2,
      "count": 1
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": false
}

### 결제 계산 성공 , 한 개, 아이템 쿠폰(고정)
### 1 = 3000 | 2 = 2000
### 예상값 = 11000
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "count": 3
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": true,
  "coupon": {
    "how": "FIXED",
    "wheres": "ITEM",
    "amount": 1000,
    "id": 2
  }
}

### 결제 계산 성공 , 한 개, 아이템 쿠폰(비율)
### 1 = 3000 | 2 = 2000
### 예상값 = 7500
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 2,
      "count": 3
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": true,
  "coupon": {
    "how": "PERCENTAGE",
    "wheres": "ITEM",
    "rate": 50,
    "id": 2
  }
}

### 결제 계산 성공 , 여러 개, 아이템 쿠폰(고정)
### 1 = 3000 | 2 = 2000
### 예상값 = 14000
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "count": 3
    },
    {
      "id": 2,
      "count": 1
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": true,
  "coupon": {
    "how": "FIXED",
    "wheres": "ITEM",
    "rate": 1000,
    "id": 1
  }
}

### 결제 계산 성공 , 여러 개, 아이템 쿠폰(비율)
### 1 = 3000 | 2 = 2000
### 예상값 = 13000
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "count": 3
    },
    {
      "id": 2,
      "count": 1
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": true,
  "coupon": {
    "how": "PERCENTAGE",
    "wheres": "ITEM",
    "rate": 50,
    "id": 2
  }
}

### 결제 계산 성공 , 여러 개, 주문 쿠폰(비율)
### 1 = 3000 | 2 = 2000
### 예상값 = 12600
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "count": 3
    },
    {
      "id": 2,
      "count": 1
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": true,
  "coupon": {
    "how": "PERCENTAGE",
    "wheres": "ORDER",
    "rate": 10,
    "id": 1
  }
}

### 결제 계산 성공 , 여러 개, 주문 쿠폰(고정)
### 1 = 3000 | 2 = 2000
### 예상값 = 12000
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "id": 1,
      "count": 3
    },
    {
      "id": 2,
      "count": 1
    }
  ],
  "deliveryPrice": 3000,
  "useCoupon": true,
  "coupon": {
    "how": "FIXED",
    "wheres": "ORDER",
    "amount": 2000,
    "id": 1
  }

}
